-- CRIE UM BANCO DE DADOS PARA UM SERVIÇO DE RH DE UMA EMPRESA, ONDE O SISTEMA TRABALHARÁ
-- COM AS INFORMAÇÕES DOS COLABORADORES DESTA EMPRESA
CREATE DATABASE DB_SERVICOS_RH; 
USE DB_SERVICOS_RH;

-- CRIE UMA TABELA DE COLABORADORES E DETERMINE 5 ATRIBUTOS RELEVANTES DOS COLABORADORES
-- PARA SE TRABALHAR COM O SERVIÇO DESTE RH
CREATE TABLE TB_COLABORADORES(
ID BIGINT(5) AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
CARGO VARCHAR(100),
SALARIO DECIMAL(10,2),
SETOR VARCHAR(100),
PRIMARY KEY (ID)
);
-- INSERINDO 5 REGISTROS
INSERT INTO TB_COLABORADORES(NOME,CARGO,SALARIO,SETOR) VALUES ("Walter White","Químico",12372.21,"Distribuição");
INSERT INTO TB_COLABORADORES(NOME,CARGO,SALARIO,SETOR) VALUES ("Saul Goodman","Advogado",15000.00,"Advocacia");
INSERT INTO TB_COLABORADORES(NOME,CARGO,SALARIO,SETOR) VALUES ("Brandon Mayhew","Plaqueiro",958.60,"Marketing");
INSERT INTO TB_COLABORADORES(NOME,CARGO,SALARIO,SETOR) VALUES ("Jesse Pinkman","Analista de Processos", 1235.50,"Produção");
INSERT INTO TB_COLABORADORES(NOME,CARGO,SALARIO,SETOR) VALUES ("Gustavo Fring","Proprietário",18975.5789,"Administração");

-- MOSTRANDO A TABELA COM TODOS OS REGISTROS
SELECT*FROM TB_COLABORADORES;

-- MOSTRANDO A TABELA COM COLABORADORES COM SALARIO>2000
SELECT*FROM TB_COLABORADORES WHERE SALARIO>2000;

-- MOSTRANDO A TABELA COM COLABORADORES COM SALARIO<2000
SELECT*FROM TB_COLABORADORES WHERE SALARIO<2000;

-- ATUALIZANDO UM REGISTRO DA TABELA
UPDATE TB_COLABORADORES SET SETOR = "Produção" WHERE ID=1
