CREATE DATABASE DB_CIDADE_DAS_CARNES;
USE DB_CIDADE_DAS_CARNES;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT(5) AUTO_INCREMENT,
CATEGORIA VARCHAR(255),
CONGELADO BOOLEAN,
PRIMARY KEY(ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT(5) AUTO_INCREMENT,
NOME VARCHAR(255),
PRECO DECIMAL (10,2),
QT BIGINT (5),
ATIVO BOOLEAN,
CATEGORIAS_ID BIGINT(5),
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID),
PRIMARY KEY(ID)
);

INSERT INTO TB_CATEGORIAS(CATEGORIA,CONGELADO) VALUES ("AVES",FALSE);
INSERT INTO TB_CATEGORIAS(CATEGORIA,CONGELADO) VALUES ("SUÍNO",FALSE);
INSERT INTO TB_CATEGORIAS(CATEGORIA,CONGELADO) VALUES ("BOVINO",FALSE);
INSERT INTO TB_CATEGORIAS(CATEGORIA,CONGELADO) VALUES ("EXÓTICO",TRUE);
INSERT INTO TB_CATEGORIAS(CATEGORIA,CONGELADO) VALUES ("PESCADOS",TRUE);

INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("PEITO DE FRANGO", 20, 10, TRUE,1);
INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("COSTELA BOVINA", 20, 30, TRUE,3);
INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("WAGYU",300,3,TRUE,3);
INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("POLVO",120,2,TRUE,5);
INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("CAPIVARA",50,3,TRUE,4);
INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("PANCETTA",20,5,TRUE,2);
INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("FRANGO INTEIRO",20,5,TRUE,1);
INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("FILÉ MIGNON",90,5,TRUE,3);


SELECT*FROM TB_CATEGORIAS;
SELECT*FROM TB_PRODUTOS;
SELECT*FROM TB_PRODUTOS WHERE PRECO>50;
SELECT*FROM TB_PRODUTOS WHERE PRECO BETWEEN 50 AND 150;
SELECT*FROM TB_PRODUTOS WHERE NOME LIKE "%C";
SELECT*FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PRODUTOS.CATEGORIAS_ID;
SELECT*FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PRODUTOS.CATEGORIAS_ID WHERE TB_CATEGORIAS.CATEGORIA = "AVES";