CREATE DATABASE DB_FARMACIA_BEM_ESTAR;
USE DB_FARMACIA_BEM_ESTAR;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT(5) AUTO_INCREMENT,
CATEGORIA VARCHAR(255) NOT NULL,
MARCA VARCHAR(255) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT(5) AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
PRECO DECIMAL (10,2) NOT NULL,
QT BIGINT(5) NOT NULL,
ATIVO BOOLEAN,
PRIMARY KEY (ID),
CATEGORIAS_ID BIGINT(5) NOT NULL,
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);

INSERT INTO TB_CATEGORIAS (CATEGORIA,MARCA) VALUES ("BIOFÁRMACO","ASTRAZENECA");
INSERT INTO TB_CATEGORIAS (CATEGORIA,MARCA) VALUES ("COSMÉTICO","IVONE");
INSERT INTO TB_CATEGORIAS (CATEGORIA,MARCA) VALUES ("MEDICAMENTO","MEDLEY");
INSERT INTO TB_CATEGORIAS (CATEGORIA,MARCA) VALUES ("MEDICAMENTO","EMS");
INSERT INTO TB_CATEGORIAS (CATEGORIA,MARCA) VALUES ("NUTRACÊUTICO","INTEGRALMÉDICA");

INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("ANTICORPO MONOCLONAL",13578.50,5,TRUE,1);
INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("LOÇÃO HIDRATANTE",29.90,30,TRUE,2);
INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("ALLEGRA",69.90,20,TRUE,3);
INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("CLOROQUINA",55.50,10,FALSE,4);
INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("PROTETOR LABIAL",2.99,10,TRUE,2);
INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("WHEY ISOLADO", 120.20,5,TRUE,5);
INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("BARRINHA PROTEICA",6.99,7,TRUE,5);
INSERT INTO TB_PRODUTOS(NOME,PRECO,QT,ATIVO,CATEGORIAS_ID) VALUES ("DIPIRONA MONOIDRATADA",4.99,50,TRUE,4);

SELECT*FROM TB_PRODUTOS;
SELECT*FROM TB_CATEGORIAS;

SELECT * FROM TB_PRODUTOS WHERE PRECO>50;
SELECT * FROM TB_PRODUTOS WHERE PRECO BETWEEN 5 AND 60;
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "%C%";

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PRODUTOS.CATEGORIAS_ID;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PRODUTOS.CATEGORIAS_ID WHERE TB_CATEGORIAS.CATEGORIA ="COSMÉTICO";

