CREATE DATABASE DB_PIZZARIA_LEGAL;
USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_PIZZAS(
ID BIGINT(5) AUTO_INCREMENT,
ATIVO BOOLEAN,
NOME VARCHAR(20) NOT NULL,
PRECO DECIMAL(4,2) NOT NULL,
VEGETARIANO BOOLEAN NOT NULL,
CATEGORIAS_ID BIGINT(5),
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);

CREATE TABLE TB_CATEGORIAS(
ID BIGINT(5) AUTO_INCREMENT,
CATEGORIA VARCHAR(10) NOT NULL,
BORDA_RECHEAVEL BOOLEAN,
TAMANHO CHAR(1),
PRIMARY KEY(ID)
);

INSERT INTO TB_CATEGORIAS(CATEGORIA,BORDA_RECHEAVEL,TAMANHO) VALUES ("SALGADA",TRUE,"G");
INSERT INTO TB_CATEGORIAS(CATEGORIA,BORDA_RECHEAVEL,TAMANHO) VALUES ("SALGADA",TRUE,"M");
INSERT INTO TB_CATEGORIAS(CATEGORIA,BORDA_RECHEAVEL,TAMANHO) VALUES ("SALGADA",TRUE,"P");
INSERT INTO TB_CATEGORIAS(CATEGORIA,BORDA_RECHEAVEL,TAMANHO) VALUES ("DOCE",FALSE,"G");
INSERT INTO TB_CATEGORIAS(CATEGORIA,BORDA_RECHEAVEL,TAMANHO) VALUES ("DOCE",FALSE,"M");
INSERT INTO TB_CATEGORIAS(CATEGORIA,BORDA_RECHEAVEL,TAMANHO) VALUES ("DOCE",FALSE,"P");

INSERT INTO TB_PIZZAS(ATIVO,NOME,PRECO,VEGETARIANO,CATEGORIAS_ID) VALUES (TRUE, "PEPPERONI", 32.50,FALSE,2);
INSERT INTO TB_PIZZAS(ATIVO,NOME,PRECO,VEGETARIANO,CATEGORIAS_ID) VALUES (TRUE,"BANANA COM CANELA",53.90,TRUE,4);
INSERT INTO TB_PIZZAS(ATIVO,NOME,PRECO,VEGETARIANO,CATEGORIAS_ID) VALUES (TRUE,"ABOBRINHA", 46.50,TRUE,2);
INSERT INTO TB_PIZZAS(ATIVO,NOME,PRECO,VEGETARIANO,CATEGORIAS_ID) VALUES (TRUE,"CALABRESA",50,TRUE,1);
INSERT INTO TB_PIZZAS(ATIVO,NOME,PRECO,VEGETARIANO,CATEGORIAS_ID) VALUES (TRUE,"MUSSARELA COM RÚCULA",60,TRUE,1);
INSERT INTO TB_PIZZAS(ATIVO,NOME,PRECO,VEGETARIANO,CATEGORIAS_ID) VALUES (TRUE,"CHOCOLATE",20,TRUE,6);
INSERT INTO TB_PIZZAS(ATIVO,NOME,PRECO,VEGETARIANO,CATEGORIAS_ID) VALUES (FALSE,"PRESUNTO COM ABACAXI",42.00,FALSE,2);
INSERT INTO TB_PIZZAS(ATIVO,NOME,PRECO,VEGETARIANO,CATEGORIAS_ID) VALUES (TRUE,"COGUMELO",32.9,TRUE,3);

SELECT*FROM TB_CATEGORIAS;
SELECT*FROM TB_PIZZAS;
SELECT*FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PIZZAS.CATEGORIAS_ID;